# Generated by Django 6.0.3 on 2026-03-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='bandeira',
            field=models.ImageField(blank=True, null=True, upload_to='bandeiras/'),
        ),
        migrations.AddField(
            model_name='pais',
            name='curiosidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='populacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
