# Generated by Django 6.0.3 on 2026-03-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0002_pais_bandeira_pais_curiosidade_pais_populacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='status',
            field=models.CharField(blank=True, choices=[('VISITEI', 'Visitei'), ('Pretendo Ir', 'PRETENDO IR'), ('NAO PRETENDO IR', 'Não Pretendo Ir')], max_length=20, null=True),
        ),
    ]
