# Generated by Django 6.0.3 on 2026-03-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0003_pais_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='curiosidade',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='status',
            field=models.CharField(blank=True, choices=[('Visitei', 'VISITEI'), ('PRETENDO IR', 'Pretendo Ir'), ('Não Pretendo Ir', 'NAO PRETENDO IR')], max_length=20, null=True),
        ),
    ]
