# Generated by Django 6.0.3 on 2026-03-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0004_alter_pais_curiosidade_alter_pais_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='status',
            field=models.CharField(blank=True, choices=[('VISITEI', 'Visitei'), ('PRETENDO IR', 'Pretendo Ir'), ('NAO PRETENDO IR', 'Não Pretendo Ir')], default='Não adicionado', max_length=20, null=True),
        ),
    ]
