# Generated by Django 6.0.3 on 2026-03-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0005_alter_pais_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='status',
            field=models.CharField(blank=True, choices=[('VISITEI', 'Visitei'), ('Pretendo Ir', 'PRETENDO IR'), ('Não Pretendo Ir', 'NAO PRETENDO IR'), ('NAO ADICIONADO', 'Não Adicionado')], default='Não adicionado', max_length=20, null=True),
        ),
    ]
